# Generated by Django 4.0.1 on 2022-02-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='reads',
            field=models.IntegerField(default=0),
        ),
    ]
